<?php
/**
 * Created by PhpStorm.
 * User: liuzhiming
 * Date: 16-8-19
 * Time: 下午3:56
 */

namespace Lib;
use Swoole;

class CentreServer  extends Swoole\Protocol\SOAServer
{
    function onWorkerStart($server, $worker_id)
    {
        if (!$server->taskworker){
            if ($worker_id == 0 ){
                //$server->task("load");
                $server->after((60-date("s"))*1000,function () use ($server){
                    $server->task("load");
                    $server->tick(60000, function () use ($server) {
                        $server->task("load");
                    });
                });
            }
            if ($worker_id == 1){
                $server->tick(1000, function () use ($server) {
                    $tasks = Tasks::getTasks();
                    $server->task($tasks);
                });
            }
        }
    }
    function onTask($serv, $task_id, $from_id, $data)
    {
        if ($data == "load"){
            Tasks::checkTasks();
        }else{
            $ret = [];
            foreach ($data as $id)
            {
                $task = LoadTasks::getTasks()->get($id);
                $tmp["id"] = $id;
                $tmp["execute"] = $task["execute"];
                $tmp["taskname"] = $task["taskname"];
                LoadTasks::getTasks()->set($id,["runStatus"=>LoadTasks::RunStatusStart,"runTimeStart"=>microtime()]);
                $ret[$id] = Robot::Run($tmp);
            }
            return $ret;
        }
        return true;
    }
    function onFinish($serv, $task_id, $data)
    {
        if (is_array($data)){
            foreach ($data as $id=>$v){
                if ($v){
                    $runStatus = LoadTasks::RunStatusToTaskSuccess;//运行成功
                }else{
                    $runStatus = LoadTasks::RunStatusToTaskFailed;//运行失败
                }
                LoadTasks::getTasks()->set($id,["runStatus"=>$runStatus,"runUpdateTime"=>microtime()]);

            }
        }
        return;
    }
    public function call($request, $header)
    {
        //初始化日志
        Flog::startLog($request['call']);
        Flog::log("call:".$request['call'].",params:".json_encode($request['params']));
        $ret =  parent::call($request, $header); // TODO: Change the autogenerated stub
        Flog::log($ret);
        Flog::endLog();
        Flog::flush();
        return $ret;
    }
}